from .about import about
from .home import home
from .login import login
from .page_not_found import page_not_found
from .register import register
from .logout import logout
from .account import account
from .new_posts import new_post
from .edit_post import update_post
from .delete_post import delete_post
from .post import post
